In [9]:
def add_numbers(x,y,z=None,flag=False):
    if flag:
        print('flag is true:')
    if z==None:
        return x+y
    else:
        return x+y+z
print(add_numbers(1,2,flag=True))
print(add_numbers(1,2,3))

6


In [10]:
x=[1,'a',2,'b']
i=0
while(i!=len(x)):
    print(x[i])
    i+=1

1
a
2
b


In [11]:
x.append(3)
x

[1, 'a', 2, 'b', 3]

In [12]:
for item in x:
    print(item)

1
a
2
b
3


In [13]:
x

[1, 'a', 2, 'b', 3]

In [14]:
i=0
while(i!=len(x)):
    print(x[i])
    i+=1

1
a
2
b
3


In [15]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [16]:
[1]*3

[1, 1, 1]

In [17]:
1 in [1,2,3]

True

In [18]:
x='this is string'
print(x[:2])

th


In [19]:
print(x[0:3])

thi


In [23]:
print(x[-6:])

string


In [24]:
print(x[3:])

s is string


In [25]:
firstname='christopher'
lastname='brooks'
print(firstname+' '+lastname)

christopher brooks


In [29]:
print(firstname*3)

christopherchristopherchristopher


In [30]:
print('chris' in firstname)

True


In [34]:
firstname='Christopher Arthur Hansen Brooks'.split(' ')[0]
lastname='Christopher Arthur Hansen Brooks'.split(' ')[-1]
firstname

'Christopher'

In [35]:
lastname

'Brooks'

In [37]:
'chris'+'2'

'chris2'

In [39]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['kevyan collins-thompson']='maher@gmail.com'

x['kevyan collins-thompson']

'maher@gmail.com'

In [41]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
maher@gmail.com


In [42]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
maher@gmail.com


In [45]:
for name,email in x.items():
    print(name)
    print(email)

Christopher Brooks

brooksch@umich.edu
Bill Gates

billg@microsoft.com
kevyan collins-thompson

maher@gmail.com


In [46]:
x= ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname,lname,email=x
fname

'Christopher'

In [47]:
lname

'Brooks'

In [48]:
email

'brooksch@umich.edu'

In [49]:
sales_record={
    'price':3.24,
    'num_items':4,
    'person':'chris'
}

sales_statement='{} bought {} items at a price of {} each for a total of {}'
sales_statement.format(sales_record['person'],
                       sales_record['num_items'],
                       sales_record['price'],
                       sales_record['price']*sales_record['num_items'])

'chris bought 4 items at a price of 3.24 each for a total of 12.96'

In [70]:
sales_record={
    'price':3.24,
    'num_items':4,
    'person':'maher'
}

sales_statement='{} bought {} items at a price of {} each for a total of {}'
sales_statement.format(sales_record['person'],sales_record['num_items'],
                      sales_record['price'],
                      sales_record['price']*sales_record['num_items'])

'maher bought 4 items at a price of 3.24 each for a total of 12.96'

In [77]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    mpg[:3]

In [78]:
len(mpg)

398

In [79]:
mpg[0].keys()

odict_keys(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name'])

In [82]:
import csv
%precision 2
with open('mpg.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))
    mpg[0]

In [83]:
len(mpg)

234

In [84]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [89]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

In [93]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

In [95]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

23.44

In [98]:
cylinders=set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [108]:
ctympgbycyl=[]
for c in cylinders:
    summpg=0
    cyltypecount=0
    for d in mpg:
        if d['cyl']==c:
            summpg+=float(d['cty'])
            cyltypecount+=1
    ctympgbycyl.append((c,summpg/cyltypecount))
ctympgbycyl.sort(key=lambda x:x[0])
ctympgbycyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [117]:
classes=set(d['class'] for d in mpg)
hwympgbyclasses=[]
for c in classes:
    sumhwympg=0
    classtypecount=0
    for d in mpg:
        if d['class']==c:
            sumhwympg+=float(d['hwy'])
            classtypecount+=1
    hwympgbyclasses.append((c,sumhwympg/classtypecount))
hwympgbyclasses.sort(key=lambda x:x[1])
hwympgbyclasses

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

In [120]:
import csv
%precision 2
with open('mpg.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))
len(mpg)

234

In [121]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [123]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

In [124]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

23.44

In [127]:
cylinders=set(d['cyl'] for d in mpg)
ctympgbycyl=[]
for c in cylinders:
    sumctympg=0
    cyltypecount=0
    for d in mpg:
        if d['cyl']==c:
            sumctympg+=float(d['cty'])
            cyltypecount+=1
    ctympgbycyl.append((c,sumctympg/cyltypecount))
ctympgbycyl.sort(key=lambda x:x[0])
ctympgbycyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [128]:
vehicleclasses=set(d['class'] for d in mpg)
hwympgbyclass=[]
for c in vehicleclasses:
    sumhwympg=0
    classtypecount=0
    for d in mpg:
        if d['class']==c:
            sumhwympg+=float(d['hwy'])
            classtypecount+=1
    hwympgbyclass.append((c,sumhwympg/classtypecount))
hwympgbyclass.sort(key=lambda x:x[1])
hwympgbyclass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

In [129]:
import datetime as dt
import time as tm


In [131]:
tm.time()

1590469794.53

In [132]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 5, 26, 11, 10, 34, 629922)

In [136]:
dtnow.year,dtnow.month,dtnow.day,dtnow.hour,dtnow.minute,dtnow.second

(2020, 5, 26, 11, 10, 34)

In [139]:
import datetime as dt
import time as tm
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow.year,dtnow.month,dtnow.day,dtnow.hour,dtnow.minute,dtnow.second

(2020, 5, 26, 11, 18, 15)

In [140]:
delta=dt.timedelta(days=100)
delta

datetime.timedelta(days=100)

In [144]:
today=dt.date.today()
today

datetime.date(2020, 5, 26)

In [145]:
today-delta

datetime.date(2020, 2, 16)

In [146]:
today>today-delta

True

In [147]:
import datetime as dt
import time as tm

In [152]:
dtnow=dt.datetime.today()
#dt.date.today()
dtnow.year,dtnow.month

(2020, 5)

In [157]:
delta=dt.timedelta(days=30)
today-delta

datetime.date(2020, 4, 26)

In [158]:
delta=dt.timedelta(days=10)
today-delta

datetime.date(2020, 5, 16)

In [171]:
class person:
    departmnet='school of information'
    def set_name(self,name):
        self.name=name
        return self.name
    def set_location(self,location):
        self.location=location
        return self.location
person1=person()
name=person1.set_name('maher')
location=person1.set_location('chittagong')
print('{} lives in {}'.format(name,location))


maher lives in chittagong


In [174]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest=map(min,store1,store2)
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In [188]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
  title=[]
  last_name=[]
  for name in person:
    title.append(name.split(' ')[0])
    last_name.append(name.split(' ')[-1])
  return title,last_name#Your answer here
titles,last_names=split_title_and_name(people)
full_name=[]
i=0
for title in titles:
    full_name.append(title+' '+last_names[i])
    i+=1
full_name


#mooc=list(map(title,last_name))


['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [189]:
my_function=lambda a,b,c:a+b
my_function(1,2,3)

3

In [200]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']
def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]
for person in people:
    print(split_title_and_name(person)==(lambda person: person.split()[0] + ' ' + person.split()[-1]))

False
False
False
False


In [197]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

True
True
True
True


In [202]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0]+' '+person.split()[-1]
for person in people:
    print(split_title_and_name(person)==(lambda x:x.split()[0]+' '+x.split()[-1])(person))


True
True
True
True


In [203]:
my_list=[]
for number in range(1,101):
    if number%2==0:
        my_list.append(number)
my_list

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [205]:
my_list=[number for number in range(1,101) if number%2==0]
my_list

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [207]:
def time_table():
    my_list=[]
    for i in range(10):
        for j in range(10):
            my_list.append(i*j)
    return my_list
time_table()==[i,j for i in range(10) and for j in range(10)]

SyntaxError: invalid syntax (<ipython-input-207-c52bb37ad20a>, line 7)

In [208]:
my_list=[i*j for i in range(10) for j in range(10)]

In [209]:
my_list

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 0,
 4,
 8,
 12,
 16,
 20,
 24,
 28,
 32,
 36,
 0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 0,
 6,
 12,
 18,
 24,
 30,
 36,
 42,
 48,
 54,
 0,
 7,
 14,
 21,
 28,
 35,
 42,
 49,
 56,
 63,
 0,
 8,
 16,
 24,
 32,
 40,
 48,
 56,
 64,
 72,
 0,
 9,
 18,
 27,
 36,
 45,
 54,
 63,
 72,
 81]

In [210]:
def time_table():
    my_list=[]
    for i in range(10):
        for j in range(10):
            my_list.append(i*j)
    return my_list
time_table()==[i*j for i in range(10)for j in range(10)]

True

In [216]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'
correct_answer=[]
for a in lowercase:
    for b in lowercase:
        for c in digits:
            for d in digits:
                correct_answer.append(a+b+c+d)
correct_answer[:50]
                

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa29',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa39',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa49']

In [213]:
correct_answer=[a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]
correct_answer[:10]

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09']

In [217]:
my_list=[a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

In [219]:
my_list[0:5]

['aa00', 'aa01', 'aa02', 'aa03', 'aa04']

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
import numpy as np
my_list=[1,2,3]
x=np.array(my_list)
x
y=np.array([4,5,6])
y

array([4, 5, 6])

In [4]:
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
n=np.arange(1,30,2)

In [15]:
n

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [16]:
n.reshape(3,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [19]:
m=np.linspace(0,4,9)
m

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [20]:
m.resize(3,3)

In [21]:
m

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [23]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [29]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [35]:
p=np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [37]:
n=np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [39]:
np.vstack((n,3*n))

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
       [ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87]])

In [40]:
p=np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [44]:
np.vstack((p,4*p))

array([[1, 1, 1],
       [1, 1, 1],
       [4, 4, 4],
       [4, 4, 4]])

In [45]:
p=np.ones((5,3),int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
np.vstack((p,3*p))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [47]:
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [48]:
np.hstack((p,3*p))

array([[1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3]])

In [49]:
import pandas as pd

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [51]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [57]:
x=[1,2,3]
x


[1, 2, 3]

In [58]:
y=[4,5,6]
y

[4, 5, 6]

In [59]:
print(x+y)

[1, 2, 3, 4, 5, 6]


In [61]:
x+y

[1, 2, 3, 4, 5, 6]

In [62]:
np.array(x+y)

array([1, 2, 3, 4, 5, 6])

In [63]:
np.add(x,y)

array([5, 7, 9])

In [65]:
np.array((x*y))

TypeError: can't multiply sequence by non-int of type 'list'

In [66]:
np.array(x)

array([1, 2, 3])

In [67]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [69]:
y=np.array([4,5,6])
y

array([4, 5, 6])

In [70]:
print(x+y)

[5 7 9]


In [71]:
print(x*y)

[ 4 10 18]


In [72]:
print(x/y)

[0.25 0.4  0.5 ]


In [73]:
print(x**2)

[1 4 9]


In [74]:
x

array([1, 2, 3])

In [75]:
y

array([4, 5, 6])

In [76]:
x.dot(y)

32

In [77]:
z=np.array([y,y**2,y**3])

In [78]:
z

array([[  4,   5,   6],
       [ 16,  25,  36],
       [ 64, 125, 216]])

In [79]:
x=np.array([[1,2,3],[4,5,6]])

In [80]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
y

array([4, 5, 6])

In [82]:
z=np.array((y,y**2))
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [83]:
z.shape

(2, 3)

In [86]:
x=z.T
x

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [87]:
x.shape

(3, 2)

In [88]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [89]:
z.dtype

dtype('int32')

In [91]:
x=z.astype('f')
x.dtype

dtype('float32')

In [92]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [93]:
x.dtype

dtype('int32')

In [94]:
x.astype('f')

array([1., 2., 3.], dtype=float32)

In [95]:
x.dtype

dtype('int32')

In [96]:
a=np.array([-4,-2,1,3,5])
a.sum()

3

In [97]:
a.max()

5

In [98]:
a.min()

-4

In [99]:
a.mean()

0.6

In [100]:
a.std()

3.2619012860600183

In [101]:
a.argmax()

4

In [102]:
a.argmin()

0

In [105]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [108]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [109]:
s[0]

0

In [110]:
s[4]

16

In [111]:
s[-1]

144

In [112]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [113]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [114]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [115]:
s[-5:-2]

array([ 64,  81, 100], dtype=int32)

In [116]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [117]:
s[-5::2]

array([ 64, 100, 144], dtype=int32)

In [118]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [119]:
s[-9::2]

array([ 16,  36,  64, 100, 144], dtype=int32)

In [121]:
s[-9::-1]

array([16,  9,  4,  1,  0], dtype=int32)

In [128]:
r=np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [140]:
r[4,4]

28

In [141]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [142]:
r[3,3:6]

array([21, 22, 23])

In [143]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [144]:
r[:-1,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [145]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [146]:
r[:5,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [147]:
r[r>30]

array([31, 32, 33, 34, 35])

In [150]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [151]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [152]:
r2[:]=0

In [153]:
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [154]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [155]:
r_copy=r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [157]:
r_copy[:]=10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [158]:
r2=r
r2

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [159]:
r2[:2,3:]=10

In [160]:
r2

array([[ 0,  0,  0, 10, 10, 10],
       [ 0,  0,  0, 10, 10, 10],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [161]:
r

array([[ 0,  0,  0, 10, 10, 10],
       [ 0,  0,  0, 10, 10, 10],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [162]:
old=np.array([[1,1,1],[1,1,1]])
old

array([[1, 1, 1],
       [1, 1, 1]])

In [163]:
new=old
new

array([[1, 1, 1],
       [1, 1, 1]])

In [164]:
new[0,:2]=0

In [165]:
new

array([[0, 0, 1],
       [1, 1, 1]])

In [166]:
old

array([[0, 0, 1],
       [1, 1, 1]])

In [169]:
old=np.arange(0,6).reshape(2,3)
new=old.copy()
new[:,0]=0
new

array([[0, 1, 2],
       [0, 4, 5]])

In [170]:
old

array([[0, 1, 2],
       [3, 4, 5]])

In [171]:
import random
test=np.random.randint(0,10,(4,3))
test

array([[1, 4, 9],
       [3, 6, 5],
       [0, 3, 9],
       [4, 9, 0]])

In [172]:
for row in test:
    print(row)

[1 4 9]
[3 6 5]
[0 3 9]
[4 9 0]


In [173]:
for i in range(len(test)):
    print(test[i])
    

[1 4 9]
[3 6 5]
[0 3 9]
[4 9 0]


In [174]:
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [1 4 9]
row 1 is [3 6 5]
row 2 is [0 3 9]
row 3 is [4 9 0]


In [175]:
test

array([[1, 4, 9],
       [3, 6, 5],
       [0, 3, 9],
       [4, 9, 0]])

In [176]:
test2=test**2
test2

array([[ 1, 16, 81],
       [ 9, 36, 25],
       [ 0,  9, 81],
       [16, 81,  0]], dtype=int32)

In [178]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[1 4 9] + [ 1 16 81] = [ 2 20 90]
[3 6 5] + [ 9 36 25] = [12 42 30]
[0 3 9] + [ 0  9 81] = [ 0 12 90]
[4 9 0] + [16 81  0] = [20 90  0]


In [179]:
for i,row in enumerate(test2):
    print('row',i,'is',row)

row 0 is [ 1 16 81]
row 1 is [ 9 36 25]
row 2 is [ 0  9 81]
row 3 is [16 81  0]


In [181]:
for i,j in zip(test,test2):
    print(i,'*',j,'=',i*j)

[1 4 9] * [ 1 16 81] = [  1  64 729]
[3 6 5] * [ 9 36 25] = [ 27 216 125]
[0 3 9] * [ 0  9 81] = [  0  27 729]
[4 9 0] * [16 81  0] = [ 64 729   0]


In [182]:
import numpy as np


In [183]:
my_list=[1,2,3,4]
np.array(my_list)

array([1, 2, 3, 4])

In [187]:
m=np.array([4,5,6,7,8,9]).reshape(3,2)
m

array([[4, 5],
       [6, 7],
       [8, 9]])

In [188]:
m.shape

(3, 2)

In [194]:
n=np.arange(0,30,2)
n.resize(5,3)
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [195]:
m=np.linspace(0,4,15).reshape(5,3)
m

array([[0.        , 0.28571429, 0.57142857],
       [0.85714286, 1.14285714, 1.42857143],
       [1.71428571, 2.        , 2.28571429],
       [2.57142857, 2.85714286, 3.14285714],
       [3.42857143, 3.71428571, 4.        ]])

In [197]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [198]:
np.zeros((5,2),int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [201]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [202]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [206]:
np.array([1,2,3]*3).reshape(3,3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [207]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [209]:
np.repeat([3,4,5],5).reshape(3,5)

array([[3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [211]:
np.ones([3,4],int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [215]:
p=np.ones([4,3],int)
np.vstack((p,3**p))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [217]:
np.hstack((p,3*p))

array([[1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3]])

In [218]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [219]:
y=np.array([4,5,6])
y

array([4, 5, 6])

In [220]:
print(x+y)

[5 7 9]


In [221]:
print(x*y)

[ 4 10 18]


In [222]:
print(x-y)

[-3 -3 -3]


In [223]:
x

array([1, 2, 3])

In [224]:
y

array([4, 5, 6])

In [225]:
x.dot(y)

32

In [227]:
z=np.array([y,y**2,y**3])
z

array([[  4,   5,   6],
       [ 16,  25,  36],
       [ 64, 125, 216]])

In [228]:
len(z)

3

In [229]:
y=z.T

In [230]:
y

array([[  4,  16,  64],
       [  5,  25, 125],
       [  6,  36, 216]])

In [231]:
y.shape

(3, 3)

In [232]:
z.dtype

dtype('int32')

In [234]:
x=z.astype('f')
x.dtype

dtype('float32')

In [235]:
a=np.array([-3,-4,-1,10,13,14])
a

array([-3, -4, -1, 10, 13, 14])

In [236]:
a.sum()

29

In [237]:
a.max()

14

In [238]:
a.min()

-4

In [239]:
a.mean()

4.833333333333333

In [240]:
a.std()

7.646713164636308

In [241]:
a.argmax()

5

In [242]:
a.argmin()

1

In [243]:
s=np.arange(13)**3

In [244]:
s

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728], dtype=int32)

In [245]:
s[4]

64

In [246]:
s[-4]

729

In [247]:
s[1:5]

array([ 1,  8, 27, 64], dtype=int32)

In [248]:
s

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728], dtype=int32)

In [249]:
s[-4:]

array([ 729, 1000, 1331, 1728], dtype=int32)

In [250]:
s[-6::-2]

array([343, 125,  27,   1], dtype=int32)

In [251]:
s[-6::2]

array([ 343,  729, 1331], dtype=int32)

In [252]:
s=np.arange(56).reshape(7,8)
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [253]:
s[4,4]

36

In [254]:
s[2,3]

19

In [255]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [257]:
s[:3,3:6]

array([[ 3,  4,  5],
       [11, 12, 13],
       [19, 20, 21]])

In [258]:
s[:2,:-1]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [259]:
s[-1,::2]

array([48, 50, 52, 54])

In [260]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [261]:
s[-1,::2]

array([48, 50, 52, 54])

In [262]:
s[s>48]

array([49, 50, 51, 52, 53, 54, 55])

In [263]:
s[s>48]=6**2

In [264]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 36, 36, 36, 36, 36, 36, 36]])

In [265]:
s1=s

In [266]:
s1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 36, 36, 36, 36, 36, 36, 36]])

In [267]:
s1[s1==36]=25

In [268]:
s1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 25, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 25, 25, 25, 25, 25, 25, 25]])

In [269]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 25, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 25, 25, 25, 25, 25, 25, 25]])

In [270]:
s2=s.copy()
s2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 25, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 25, 25, 25, 25, 25, 25, 25]])

In [271]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 25, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 25, 25, 25, 25, 25, 25, 25]])

In [272]:
s2[s2==25]=30
s2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 30, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 30, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 30, 30, 30, 30, 30, 30, 30]])

In [273]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 25, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 25, 25, 25, 25, 25, 25, 25]])

In [277]:
test=np.random.randint(1,10,200).reshape(10,20)
test

array([[9, 3, 9, 1, 6, 6, 6, 1, 7, 6, 9, 9, 9, 7, 3, 4, 8, 4, 8, 1],
       [4, 3, 9, 3, 6, 7, 1, 6, 6, 3, 5, 8, 6, 5, 8, 5, 4, 1, 9, 4],
       [2, 6, 2, 7, 4, 9, 9, 6, 8, 7, 1, 7, 6, 9, 4, 7, 5, 6, 3, 4],
       [8, 1, 4, 1, 3, 4, 3, 4, 1, 5, 8, 9, 2, 7, 1, 2, 4, 6, 4, 4],
       [5, 7, 6, 8, 8, 6, 3, 9, 7, 5, 5, 8, 5, 4, 8, 3, 3, 3, 2, 8],
       [2, 4, 8, 5, 3, 1, 6, 6, 8, 8, 3, 9, 3, 8, 6, 8, 5, 3, 9, 1],
       [7, 5, 4, 7, 3, 6, 3, 8, 9, 3, 6, 1, 7, 2, 6, 7, 8, 5, 4, 6],
       [9, 5, 5, 4, 3, 1, 5, 2, 3, 4, 3, 7, 9, 9, 1, 4, 4, 6, 7, 1],
       [6, 4, 1, 7, 5, 7, 3, 8, 8, 2, 1, 5, 8, 8, 6, 1, 6, 3, 6, 9],
       [8, 5, 9, 5, 5, 4, 5, 9, 5, 3, 1, 9, 6, 3, 8, 9, 1, 4, 9, 6]])

In [278]:
test2=test**2
test2

array([[81,  9, 81,  1, 36, 36, 36,  1, 49, 36, 81, 81, 81, 49,  9, 16,
        64, 16, 64,  1],
       [16,  9, 81,  9, 36, 49,  1, 36, 36,  9, 25, 64, 36, 25, 64, 25,
        16,  1, 81, 16],
       [ 4, 36,  4, 49, 16, 81, 81, 36, 64, 49,  1, 49, 36, 81, 16, 49,
        25, 36,  9, 16],
       [64,  1, 16,  1,  9, 16,  9, 16,  1, 25, 64, 81,  4, 49,  1,  4,
        16, 36, 16, 16],
       [25, 49, 36, 64, 64, 36,  9, 81, 49, 25, 25, 64, 25, 16, 64,  9,
         9,  9,  4, 64],
       [ 4, 16, 64, 25,  9,  1, 36, 36, 64, 64,  9, 81,  9, 64, 36, 64,
        25,  9, 81,  1],
       [49, 25, 16, 49,  9, 36,  9, 64, 81,  9, 36,  1, 49,  4, 36, 49,
        64, 25, 16, 36],
       [81, 25, 25, 16,  9,  1, 25,  4,  9, 16,  9, 49, 81, 81,  1, 16,
        16, 36, 49,  1],
       [36, 16,  1, 49, 25, 49,  9, 64, 64,  4,  1, 25, 64, 64, 36,  1,
        36,  9, 36, 81],
       [64, 25, 81, 25, 25, 16, 25, 81, 25,  9,  1, 81, 36,  9, 64, 81,
         1, 16, 81, 36]], dtype=int32)

In [279]:
for row in test:
    print(row)

[9 3 9 1 6 6 6 1 7 6 9 9 9 7 3 4 8 4 8 1]
[4 3 9 3 6 7 1 6 6 3 5 8 6 5 8 5 4 1 9 4]
[2 6 2 7 4 9 9 6 8 7 1 7 6 9 4 7 5 6 3 4]
[8 1 4 1 3 4 3 4 1 5 8 9 2 7 1 2 4 6 4 4]
[5 7 6 8 8 6 3 9 7 5 5 8 5 4 8 3 3 3 2 8]
[2 4 8 5 3 1 6 6 8 8 3 9 3 8 6 8 5 3 9 1]
[7 5 4 7 3 6 3 8 9 3 6 1 7 2 6 7 8 5 4 6]
[9 5 5 4 3 1 5 2 3 4 3 7 9 9 1 4 4 6 7 1]
[6 4 1 7 5 7 3 8 8 2 1 5 8 8 6 1 6 3 6 9]
[8 5 9 5 5 4 5 9 5 3 1 9 6 3 8 9 1 4 9 6]


In [280]:
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [9 3 9 1 6 6 6 1 7 6 9 9 9 7 3 4 8 4 8 1]
row 1 is [4 3 9 3 6 7 1 6 6 3 5 8 6 5 8 5 4 1 9 4]
row 2 is [2 6 2 7 4 9 9 6 8 7 1 7 6 9 4 7 5 6 3 4]
row 3 is [8 1 4 1 3 4 3 4 1 5 8 9 2 7 1 2 4 6 4 4]
row 4 is [5 7 6 8 8 6 3 9 7 5 5 8 5 4 8 3 3 3 2 8]
row 5 is [2 4 8 5 3 1 6 6 8 8 3 9 3 8 6 8 5 3 9 1]
row 6 is [7 5 4 7 3 6 3 8 9 3 6 1 7 2 6 7 8 5 4 6]
row 7 is [9 5 5 4 3 1 5 2 3 4 3 7 9 9 1 4 4 6 7 1]
row 8 is [6 4 1 7 5 7 3 8 8 2 1 5 8 8 6 1 6 3 6 9]
row 9 is [8 5 9 5 5 4 5 9 5 3 1 9 6 3 8 9 1 4 9 6]


In [281]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i*j)

[9 3 9 1 6 6 6 1 7 6 9 9 9 7 3 4 8 4 8 1] + [81  9 81  1 36 36 36  1 49 36 81 81 81 49  9 16 64 16 64  1] = [729  27 729   1 216 216 216   1 343 216 729 729 729 343  27  64 512  64
 512   1]
[4 3 9 3 6 7 1 6 6 3 5 8 6 5 8 5 4 1 9 4] + [16  9 81  9 36 49  1 36 36  9 25 64 36 25 64 25 16  1 81 16] = [ 64  27 729  27 216 343   1 216 216  27 125 512 216 125 512 125  64   1
 729  64]
[2 6 2 7 4 9 9 6 8 7 1 7 6 9 4 7 5 6 3 4] + [ 4 36  4 49 16 81 81 36 64 49  1 49 36 81 16 49 25 36  9 16] = [  8 216   8 343  64 729 729 216 512 343   1 343 216 729  64 343 125 216
  27  64]
[8 1 4 1 3 4 3 4 1 5 8 9 2 7 1 2 4 6 4 4] + [64  1 16  1  9 16  9 16  1 25 64 81  4 49  1  4 16 36 16 16] = [512   1  64   1  27  64  27  64   1 125 512 729   8 343   1   8  64 216
  64  64]
[5 7 6 8 8 6 3 9 7 5 5 8 5 4 8 3 3 3 2 8] + [25 49 36 64 64 36  9 81 49 25 25 64 25 16 64  9  9  9  4 64] = [125 343 216 512 512 216  27 729 343 125 125 512 125  64 512  27  27  27
   8 512]
[2 4 8 5 3 1 6 6 8 8 3 9 3 8 6 8 5 3 9 1] + [

In [282]:
def add_numbers(x,y):
    return x+y
add_numbers(3,4)

7

In [289]:
def add_numbers(x,y,z=None,flag=True):
    if (flag):
        print('flag is true')
    if z==None:
        return x+y
    else:
        return x+y+z
add_numbers(1,2)

flag is true


3

In [284]:
add_numbers(3,4,5)

12

In [290]:
x=[1,2,3,4]
x.append(5)
x

[1, 2, 3, 4, 5]

In [291]:
for item in x:
    print(item)

1
2
3
4
5


In [292]:
for i in range(len(x)):
    print(x[i])

1
2
3
4
5


In [293]:
i=0
while (i<len(x)):
    print(x[i])
    i+=1

1
2
3
4
5


In [294]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [295]:
[1,2,3,4]*4

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [296]:
4 in x

True

In [297]:
x='this is a string'
x[0]

't'

In [298]:
x[-1]

'g'

In [299]:

x[-4:-2]
x

'this is a string'

In [301]:
x[-4:-2]

'ri'

In [302]:
x[:6]

'this i'

In [303]:
x[4:]

' is a string'

In [304]:
firstname = 'Christopher'
lastname = 'Brooks'


In [305]:
print(firstname+' '+lastname)

Christopher Brooks


In [306]:
print(firstname*3)

ChristopherChristopherChristopher


In [308]:
print('Chris' in firstname)

True


In [309]:
firstname = 'Christopher Arthur Hansen Brooks'
firstname.split(' ')[1]

'Arthur'

In [310]:
lastname = 'Christopher Arthur Hansen Brooks'
lastname.split(' ')[-1]

'Brooks'

In [311]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks']

'brooksch@umich.edu'

In [312]:
x['Kevyn Collins-Thompson']=None
x['Kevyn Collins-Thompson']

In [313]:
for name in x:
    print(name)

Christopher Brooks
Bill Gates
Kevyn Collins-Thompson


In [314]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


In [315]:
for name,email in x.items():
    print(name,':',email)

Christopher Brooks : brooksch@umich.edu
Bill Gates : billg@microsoft.com
Kevyn Collins-Thompson : None


In [319]:
x=('maher','ibne','rahman')
first,middle,last=x
first
middle
last

'rahman'

In [322]:
sales_record={
    'person':'maher',
    'price':4,
    'num_items':12
}
sales_statement='{} bought {} items at a price of {} each for a total of {} '
print(sales_statement.format(sales_record['person'],sales_record['num_items'],sales_record['price'],
                            sales_record['price']*sales_record['num_items']))

maher bought 12 items at a price of 4 each for a total of 48 


In [9]:
import csv
%precision 2

'%.2f'

In [10]:
with open('mpg.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))
    mpg

In [11]:
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [12]:
len(mpg)

234

In [13]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [14]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

In [15]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

23.44

In [18]:
cylinders=set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [19]:
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [27]:
avgctympgbycyl=[]

for c in cylinders:
    avgctympg=0
    cylcount=0
    for d in mpg:
         if d['cyl']==c:
            avgctympg+=float(d['cty'])
            cylcount+=1
    avgctympgbycyl.append((c,avgctympg/cylcount))
avgctympgbycyl.sort(key=lambda x:x[0])
avgctympgbycyl
        
        

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [28]:
vehicleclass=set(d['class'] for d in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [30]:
avghwympgbyclass=[]
for c in vehicleclass:
    avghwympg=0
    classcount=0
    for d in mpg:
        if d['class']==c:
            avghwympg+=float(d['hwy'])
            classcount+=1
    avghwympgbyclass.append((c,avghwympg/classcount))
avghwympgbyclass.sort(key=lambda x:x[1])
avghwympgbyclass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

In [31]:
import datetime as dt
import time as tm

In [32]:
tm.time()

1590821337.26

In [33]:
dtnow=dt.datetime.fromtimestamp(tm.time())

In [34]:
dtnow

datetime.datetime(2020, 5, 30, 12, 51, 25, 773345)

In [35]:
dtnow.year

2020

In [36]:
dtnow.day

30

In [37]:
dtnow.second

25

In [38]:
delta=dt.timedelta(days=100)
delta

datetime.timedelta(days=100)

In [39]:
today=dt.date.today()
today

datetime.date(2020, 5, 30)

In [40]:
today-delta

datetime.date(2020, 2, 20)

In [41]:
class person:
    department='ECE'
    def set_name(self,name):
        self.name=name
    def set_location(self,location):
        self.location=location
person=person()
person.set_name('maher')
person.set_location('chittagong')
print('{} lives in {} and works in the department of {}'.format(person.name,person.location,person.department))

maher lives in chittagong and works in the department of ECE


In [42]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]


In [45]:
cheapest=map(max,store1,store2)
cheapest

In [46]:
for item in cheapest:
    print(item)

10.0
11.1
12.34
2.34


In [47]:
my_func=lambda a,b,c:a+b+c
my_func(2,3,4)

9

In [57]:
func=lambda first,last:first.upper()+' '+last.upper()
func('maher','rahman')
type(func)

function

In [50]:
my_list=[number for number in range(1,101) if number%2==0]

In [51]:
my_list

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [56]:
str='maher'
str[0]='l'


TypeError: 'str' object does not support item assignment